import os
Import('env')

menv = env.Clone()
menv.Append(CPPPATH=['#lib'])

lib = env.Glob("#lib/*.os")
src = env.Glob("test*.c") + env.Glob("test*.cpp")
prg = [menv.Program(os.path.splitext(str(f))[0], [f] + lib) for f in src]
env.Alias('test',prg)

