import os
Import('env libname')

menv = env.Clone()
menv.Append(CPPPATH=['#lib'],
            LIBPATH=['#lib'],
            LIBS=[libname])

src = env.Glob("test*.c") + env.Glob("test*.cpp")
prg = [menv.Program(os.path.splitext(str(f))[0], f) for f in src]
env.Alias('test',prg)

