import os
Import('env drvname')

menv = env.Clone()
menv.Append(CPPPATH=['#driver'],
            LIBPATH=['#driver'],
            LIBS=[drvname])

src = env.Glob("test*.c") + env.Glob("test*.cpp")
prg = [menv.Program(os.path.splitext(str(f))[0], f) for f in src]
env.Alias('test',prg)

